### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JunaidGH** [ericfitz/Inspector-Agent-Autodeploy#2]
Hi i am getting the following error message, not sure what the error mean, can you advice.

```
list index out of range: IndexError
Traceback (most recent call last):
  File "/var/task/index.py", line 53, in lambda_handler
    instanceInfo = response['InstanceInformationList'][0]
IndexError: list index out of range
```

**Comment by ericfitz** [comment]
The "list index out of range" error is almost always caused by not having the right permissions in the IAM policy attached to the Lambda function.
